routes/web.php
<?php

use App\Http\Controllers\BidangController;
use App\Http\Controllers\BoxController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\MapController;
use App\Http\Controllers\RakController;
use App\Http\Controllers\RuanganController;
use App\Http\Controllers\SkpdController;
use App\Http\Controllers\TransactionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::resource('ruangans', RuanganController::class);
    Route::resource('raks', RakController::class);
    Route::resource('boxes', BoxController::class);
    Route::resource('maps', MapController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('bidangs', BidangController::class);
    Route::resource('skpds', SkpdController::class);
    Route::resource('documents', DocumentController::class);
    Route::resource('users', UserController::class);

    Route::get('/check-document', [DocumentController::class, 'showCheckDocumentForm'])->name('checkDocument');
    Route::put('documents/{document}/update-completed', [DocumentController::class, 'updateCompleted'])->name('updateCompeleted');

    Route::get('pinjam', [TransactionController::class, 'pinjam'])->name('pinjam');
    Route::get('kembali', [TransactionController::class, 'kembali'])->name('kembali');
    Route::get('transactions', [TransactionController::class, 'index'])->name('transactions');
    Route::post('submit_documents', [TransactionController::class, 'submitDocuments'])->name('submit_documents');
    Route::post('return_documents', [TransactionController::class, 'returnDocuments'])->name('return_documents');
});

app/Models/Rak.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Rak extends Model
{
    use HasFactory;

    protected $fillable = ['ruangan_id', 'kode_rak'];

}

app/Http/Controllers/RakController.php
<?php

namespace App\Http\Controllers;

use App\Models\Rak;
use Illuminate\Http\Request;

class RakController extends Controller
{
    public function index()
    {
        $raks = Rak::all();
        return view('be.raks.index', compact('raks'));
    }

    public function create()
    {
        return view('be.raks.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'kode_rak' => 'required|unique:raks',
        ]);

        Rak::create($validatedData);

        return redirect('/raks')->with('success', 'Rak berhasil dibuat.');
    }

    public function edit(Rak $rak)
    {

        return view('be.raks.edit', compact('rak'));
    }

    public function update(Request $request, Rak $rak)
    {
        $validatedData = $request->validate([
            'kode_rak' => 'required|unique:raks,kode_rak,' . $rak->id,
        ]);

        $rak->update($validatedData);

        return redirect('/raks')->with('success', 'Rak berhasil diperbarui.');
    }

    public function destroy(Rak $rak)
    {
        $rak->delete();

        return redirect('/raks')->with('success', 'Rak berhasil dihapus.');
    }
}

resources/views/be/raks/create.blade.php
@extends('layouts.backend.app')
@php
    $title = 'Rak';
@endphp
@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">{{ $title ?? '' }}</a></li>
    </ol>
    <!-- END breadcrumb -->
    <!-- BEGIN page-header -->
    {{-- <h1 class="page-header">Blank Page <small>header small text goes here...</small></h1> --}}
    <!-- END page-header -->
    <!-- BEGIN panel -->
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title">{{ $title ?? '' }}</h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i
                        class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i
                        class="fa fa-redo"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-warning" data-toggle="panel-collapse"><i
                        class="fa fa-minus"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-danger" data-toggle="panel-remove"><i
                        class="fa fa-times"></i></a>
            </div>
        </div>
        <div class="panel-body">
            <form action="{{ route('raks.store') }}" method="POST">
                @csrf
                <fieldset>
                    <legend class="mb-3">Rak Create</legend>

                    {{-- <div class="mb-3">
                        <label class="form-label" for="ruangan_id">Ruangan</label>
                        <select class="form-control @error('ruangan_id') is-invalid @enderror" id="ruangan_id"
                            name="ruangan_id">
                            <option value="">Pilih Ruangan</option>
                            @foreach ($ruangans as $ruangan)
                                <option value="{{ $ruangan->id }}">{{ $ruangan->nama }}</option>
                            @endforeach
                        </select>
                        @error('ruangan_id')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div> --}}

                    <div class="mb-3">
                        <label class="form-label" for="kode_rak">Kode Rak</label>
                        <input class="form-control @error('kode_rak') is-invalid @enderror" type="text" id="kode_rak"
                            name="kode_rak" placeholder="Enter kode rak" value="{{ old('kode_rak') }}">
                        @error('kode_rak')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary">Simpan</button>
                </fieldset>
            </form>
        </div>
    </div>
@endsection

resources/views/be/raks/edit.blade.php
@extends('layouts.backend.app')
@php
    $title = 'Rak';
@endphp
@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">{{ $title ?? '' }}</a></li>
    </ol>
    <!-- END breadcrumb -->
    <!-- BEGIN page-header -->
    {{-- <h1 class="page-header">Blank Page <small>header small text goes here...</small></h1> --}}
    <!-- END page-header -->
    <!-- BEGIN panel -->
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title">{{ $title ?? '' }}</h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i
                        class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i
                        class="fa fa-redo"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-warning" data-toggle="panel-collapse"><i
                        class="fa fa-minus"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-danger" data-toggle="panel-remove"><i
                        class="fa fa-times"></i></a>
            </div>
        </div>
        <div class="panel-body">
            <form action="{{ route('raks.update', $rak->id) }}" method="POST">
                @csrf
                @method('PUT')
                <fieldset>
                    <legend class="mb-3">Rak Edit</legend>

                    {{-- <div class="mb-3">
                        <label class="form-label" for="ruangan_id">Ruangan</label>
                        <select class="form-control @error('ruangan_id') is-invalid @enderror" id="ruangan_id"
                            name="ruangan_id">
                            <option value="">Pilih Ruangan</option>
                            @foreach ($ruangans as $ruangan)
                                <option value="{{ $ruangan->id }}" @if ($rak->ruangan_id == $ruangan->id) selected @endif>
                                    {{ $ruangan->nama }}</option>
                            @endforeach
                        </select>
                        @error('ruangan_id')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div> --}}

                    <div class="mb-3">
                        <label class="form-label" for="kode_rak">Kode Rak</label>
                        <input class="form-control @error('kode_rak') is-invalid @enderror" type="text" id="kode_rak"
                            name="kode_rak" placeholder="Enter kode rak" value="{{ old('kode_rak', $rak->kode_rak) }}">
                        @error('kode_rak')
                            <div class="invalid-feedback">{{ $message }}</div>
                        @enderror
                    </div>

                    <button type="submit" class="btn btn-primary">Update</button>
                </fieldset>
            </form>
        </div>
    </div>
@endsection

resources/views/be/raks/index.blade.php
@extends('layouts.backend.app')

@php
    $title = 'Rak';
@endphp

@push('styles')
    <link href="{{ asset('assets/be/plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('assets/be/plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css') }}"
        rel="stylesheet" />
    <link href="{{ asset('assets/be/plugins/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css') }}"
        rel="stylesheet" />
@endpush
@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:;">Home</a></li>
        <li class="breadcrumb-item"><a href="javascript:;">{{ $title ?? '' }}</a></li>
    </ol>
    <!-- END breadcrumb -->
    <!-- BEGIN page-header -->
    <h1 class="page-header">{{ $title ?? '' }}</h1>
    <!-- END page-header -->
    <!-- BEGIN panel -->
    <div class="panel panel-inverse">
        <div class="panel-heading">
            <h4 class="panel-title">{{ $title ?? '' }}</h4>
            <div class="panel-heading-btn">
                <a href="javascript:;" class="btn btn-xs btn-icon btn-default" data-toggle="panel-expand"><i
                        class="fa fa-expand"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-success" data-toggle="panel-reload"><i
                        class="fa fa-redo"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-warning" data-toggle="panel-collapse"><i
                        class="fa fa-minus"></i></a>
                <a href="javascript:;" class="btn btn-xs btn-icon btn-danger" data-toggle="panel-remove"><i
                        class="fa fa-times"></i></a>
                <a href="{{ route('raks.create') }}" class="btn btn-primary btn-xs"><i class="fa fa-plus"></i></a>
            </div>
        </div>
        <div class="panel-body">
            <table id="table" class="table table-striped table-bordered align-middle">
                <thead>
                    <tr>
                        <th width="1%">No.</th>
                        <th class="text-nowrap">Kode Rak</th>
                        <th class="text-nowrap"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($raks as $rak)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $rak->kode_rak }}</td>
                            <td>
                                <a href="{{ route('raks.edit', $rak->id) }}" class="btn btn-warning">
                                    <i class="fas fa-edit"></i> Edit
                                </a>
                                <form action="{{ route('raks.destroy', $rak->id) }}" method="POST"
                                    style="display: inline">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger"
                                        onclick="return confirm('Apakah Anda yakin ingin menghapus rak ini?')">
                                        <i class="fas fa-trash-alt"></i> Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script src="{{ asset('assets/be/plugins/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/datatables.net-buttons/js/buttons.colVis.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/pdfmake/build/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/be/plugins/jszip/dist/jszip.min.js') }}"></script>

    <script>
        $('#table').DataTable({
            responsive: true,
            dom: '<"row"<"col-sm-5"B><"col-sm-7"fr>>t<"row"<"col-sm-5"i><"col-sm-7"p>>',
            buttons: [{
                    extend: 'csv',
                    className: 'btn-sm'
                },
                {
                    extend: 'excel',
                    className: 'btn-sm'
                },

            ],
        });
    </script>
@endpush